### ISSUE TITLE
csv files in Testing_Historical_Data.ipynb

### ISSUE THREAD

**Issue by josh0tt** [juliansester/Deep-Arbitrage#1]
The csv files used in Testing_Historical_Data.ipynb do not seem to be defined anywhere. How are they generated / what is their format?

```
Asset_1  = pd.read_csv("data/Apple.csv", header=None)
Asset_2 = pd.read_csv("data/Google.csv", header=None)
Asset_3  = pd.read_csv("data/Facebook.csv", header=None)
Asset_4  = pd.read_csv("data/Microsoft.csv", header=None)
Asset_5  = pd.read_csv("data/Amazon.csv", header=None)
closing_prices  = pd.read_csv("data/closing_prices.csv", header=None)
```

**Comment by juliansester** [comment]
Thanks for the comment.

Since the original *.csv-files contain data downloaded from Bloomberg, we can unfortunately NOT provide them here. 

I just uploaded some DUMMY-*.csv files showcasing the structure of the used data.  I hope this helps!

Best,
Julian

**Comment by josh0tt** [comment]
Thanks for the response and uploading the files, that was very helpful! 

Just curious, why not also use the yfinance `option_chain()` to get this data instead?

**Comment by juliansester** [comment]
Dear josh0tt,

unfortunately, with option_chain() one can only download current option prices, but not **historical** option prices.
One certainly could apply option_chain() on a daily basis over a period of time and collect the results. But, directly, this is to the best of my knowledge not possible with yahoo finance.

Best,
Julian

**Comment by josh0tt** [comment]
Ah yeah, that makes sense. Thank you for the quick response!
